### ISSUE TITLE
level=error msg="Could not unmarshal JSON: unexpected end of JSON input" 

### ISSUE THREAD

**Issue by TableMountain** [nii236/oanda#1]
Haven't pried into the code about it but I'm pretty sure I put the account and token in. Any thoughts why this is happening?

**Comment by TableMountain** [comment]
Not sure why Oanda won't return JSON, or an error or something i'll have to check their enpoint

**Comment by TableMountain** [comment]
I realized It's because I don't have a v20 account...
I have a legacy account

**Comment by nii236** [comment]
Thanks for the report! I need to improve the error handling in this package so it is clearer.

Please use [this package](https://github.com/santegoeds/oanda) for the older REST API.
